language: java
before_install:
  # download the latest android sdk and unzip
  - wget http://dl.google.com/android/android-sdk_r21-linux.tgz
  - tar -zxf android-sdk_r21-linux.tgz
  # setup your ANDROID_HOME and PATH environment variables
  # use ~/builds/[Github username]/[project]/android-sdk-linux
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - android list sdk -a
  - android update sdk --filter 1,2,11,12,13,14 --no-ui --force
  - ls ${ANDROID_HOME}/platform-tools
  - ls -l /home/travis/build/kovmarci86/android-secure-preferences/secure-storage-sample-app
  - ls -l /home/travis/build/kovmarci86/android-secure-preferences/android-sdk-linux/platform-tools/
  - ls -l /home/travis/build/kovmarci86/android-secure-preferences/android-sdk-linux/platforms/
  - /home/travis/build/kovmarci86/android-secure-preferences/android-sdk-linux/platform-tools/aapt
  
install: mvn clean install -Dandroid.test.skip=true -X
